variables:
  DOCKER_REGISTRY: 557578698015.dkr.ecr.us-east-2.amazonaws.com
  AWS_DEFAULT_REGION: us-east-2
  APP_NAME: github-test
  DOCKER_HOST: tcp://docker:2375

publish:
  script: |
    chmod +x ./qualiti-test-run.sh
    . ./qualiti-test-run.sh
    
