name: "PR Merged CI (Deploy All)"

on:
  workflow_dispatch:

jobs:
  bronzeDataService:
    runs-on: ubuntu-latest
    steps:

      - name: Promote Artifacts (Bronze to Silver)
        if: cat tools/artifacts.tmp | grep Lambdas == 'Lambdas'
        run: echo Lambdas

      - name: Promote Artifacts (Bronze to Silver Backfill)
        if: cat tools/artifacts.tmp | grep Jobs == 'Jobs'
        run: echo Jobs