name: "PR Merged CI (Deploy All)"

on:
  workflow_dispatch:

jobs:
  bronzeDataService:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Detect Build Artifact(s)
        id: artifact
        run: |
            export JOBS=$(grep Lambdas tools/artifacts.tmp)
            export LAMBDAS=$(grep Jobs tools/artifacts.tmp)
            echo "jobs=$JOBS" >> $GITHUB_OUTPUT
            echo "lambdas=$LAMBDAS" >> $GITHUB_OUTPUT

      - name: Promote Artifacts (Bronze to Silver)
        if: ${{ steps.artifact.outputs.lambdas }} == 'Lambdas'
        run: echo ${{ steps.artifact.outputs.lambdas }}

      - name: Promote Artifacts (Bronze to Silver Backfill)
        if: ${{ steps.artifact.outputs.job }} == 'potato'
        run: echo ${{ steps.artifact.outputs.jobs }}