name: "PR Merged CI (Deploy All)"

on:
  workflow_dispatch:

jobs:
  bronzeDataService:
    runs-on: ubuntu-latest
    steps:

      - name: Detect Build Artifact(s)
        id: artifact
        run: |
            1=`pwd`
            echo $1
            2='ls' 
            echo $2
            export JOBS=$(grep Lambdas tools/artifacts.tmp); exit 0
            export LAMBDAS=$(grep Jobs tools/artifacts.tmp); exit 0
            echo "jobs=$JOBS" >> $GITHUB_OUTPUT
            echo "lambdas=$LAMBDAS" >> $GITHUB_OUTPUT

      - name: Promote Artifacts (Bronze to Silver)
        if: steps.artifact.outputs.lambdas == 'Lambdas'
        run: echo Lambdas

      - name: Promote Artifacts (Bronze to Silver Backfill)
        if: steps.artifact.outputs.lambdas == 'potato'
        run: echo Jobs