# TODO: Make this part of PR CI once this is working consistently

name: Github Integration - Bash Script CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run our github integration qualiti-script test
        run: |
           chmod +x .github/workflows/m.sh
           . .github/workflows/m.sh {{secrets.API_KEY}} {{secrets.CLIENT_ID}}
